// <auto-generated />
using System;
using System.Net;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PortaBox.Infrastructure.Persistence;

#nullable disable

namespace PortaBox.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260420154647_AddBlocoAndUnidade")]
    partial class AddBlocoAndUnidade
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_role_claims");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_asp_net_role_claims_role_id");

                    b.ToTable("asp_net_role_claims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_user_claims");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_asp_net_user_claims_user_id");

                    b.ToTable("asp_net_user_claims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text")
                        .HasColumnName("provider_key");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text")
                        .HasColumnName("provider_display_name");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("LoginProvider", "ProviderKey")
                        .HasName("pk_asp_net_user_logins");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_asp_net_user_logins_user_id");

                    b.ToTable("asp_net_user_logins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.HasKey("UserId", "RoleId")
                        .HasName("pk_asp_net_user_roles");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_asp_net_user_roles_role_id");

                    b.ToTable("asp_net_user_roles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Value")
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("UserId", "LoginProvider", "Name")
                        .HasName("pk_asp_net_user_tokens");

                    b.ToTable("asp_net_user_tokens", (string)null);
                });

            modelBuilder.Entity("PortaBox.Infrastructure.Email.EmailOutboxEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Attempts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("attempts");

                    b.Property<string>("HtmlBody")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("html_body");

                    b.Property<string>("LastError")
                        .HasColumnType("text")
                        .HasColumnName("last_error");

                    b.Property<DateTimeOffset>("NextAttemptAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_attempt_at");

                    b.Property<DateTimeOffset?>("SentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_at");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("subject");

                    b.Property<string>("TextBody")
                        .HasColumnType("text")
                        .HasColumnName("text_body");

                    b.Property<string>("ToAddress")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("to_address");

                    b.HasKey("Id")
                        .HasName("pk_email_outbox");

                    b.HasIndex("SentAt", "NextAttemptAt")
                        .HasDatabaseName("idx_email_outbox_sent_at_next_attempt_at");

                    b.ToTable("email_outbox", (string)null);
                });

            modelBuilder.Entity("PortaBox.Infrastructure.Events.DomainEventOutboxEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AggregateId")
                        .HasColumnType("uuid")
                        .HasColumnName("aggregate_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("event_type");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_domain_event_outbox");

                    b.HasIndex("PublishedAt", "CreatedAt")
                        .HasDatabaseName("idx_domain_event_outbox_published_at_created_at");

                    b.ToTable("domain_event_outbox", (string)null);
                });

            modelBuilder.Entity("PortaBox.Infrastructure.Identity.AppRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_name");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_roles");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("ix_asp_net_roles_normalized_name");

                    b.ToTable("asp_net_roles", (string)null);
                });

            modelBuilder.Entity("PortaBox.Infrastructure.Identity.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer")
                        .HasColumnName("access_failed_count");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("email_confirmed");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("lockout_enabled");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lockout_end");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_user_name");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("phone_number_confirmed");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text")
                        .HasColumnName("security_stamp");

                    b.Property<Guid?>("SindicoTenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("sindico_tenant_id");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("two_factor_enabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("user_name");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_users");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("ix_asp_net_users_normalized_email");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("ix_asp_net_users_normalized_user_name");

                    b.HasIndex("SindicoTenantId")
                        .HasDatabaseName("ix_asp_net_users_sindico_tenant_id");

                    b.ToTable("asp_net_users", (string)null);
                });

            modelBuilder.Entity("PortaBox.Infrastructure.MagicLinks.MagicLink", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ConsumedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("consumed_at");

                    b.Property<IPAddress>("ConsumedByIp")
                        .HasColumnType("inet")
                        .HasColumnName("consumed_by_ip");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<DateTimeOffset?>("InvalidatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("invalidated_at");

                    b.Property<short>("Purpose")
                        .HasColumnType("smallint")
                        .HasColumnName("purpose");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("character(64)")
                        .HasColumnName("token_hash")
                        .IsFixedLength();

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_magic_link");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("idx_magic_link_token_hash_unique");

                    b.HasIndex("UserId", "Purpose")
                        .HasDatabaseName("idx_magic_link_user_purpose_open")
                        .HasFilter("consumed_at IS NULL AND invalidated_at IS NULL");

                    b.ToTable("magic_link", (string)null);
                });

            modelBuilder.Entity("PortaBox.Modules.Gestao.Domain.Blocos.Bloco", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<Guid>("CondominioId")
                        .HasColumnType("uuid")
                        .HasColumnName("condominio_id");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<Guid>("CriadoPor")
                        .HasColumnType("uuid")
                        .HasColumnName("criado_por");

                    b.Property<DateTime?>("InativadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("inativado_em");

                    b.Property<Guid?>("InativadoPor")
                        .HasColumnType("uuid")
                        .HasColumnName("inativado_por");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nome");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_bloco");

                    b.HasIndex("CondominioId")
                        .HasDatabaseName("idx_bloco_condominio");

                    b.HasIndex("CriadoPor")
                        .HasDatabaseName("ix_bloco_criado_por");

                    b.HasIndex("InativadoPor")
                        .HasDatabaseName("ix_bloco_inativado_por");

                    b.HasIndex("TenantId", "CondominioId", "Nome")
                        .IsUnique()
                        .HasDatabaseName("idx_bloco_nome_ativo_unique")
                        .HasFilter("ativo = true");

                    b.ToTable("bloco", (string)null);
                });

            modelBuilder.Entity("PortaBox.Modules.Gestao.Domain.Condominio", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ActivatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("activated_at");

                    b.Property<Guid?>("ActivatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("activated_by_user_id");

                    b.Property<string>("AdministradoraNome")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("administradora_nome");

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasColumnType("character(14)")
                        .HasColumnName("cnpj")
                        .IsFixedLength();

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("EnderecoBairro")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("endereco_bairro");

                    b.Property<string>("EnderecoCep")
                        .HasColumnType("character(8)")
                        .HasColumnName("endereco_cep")
                        .IsFixedLength();

                    b.Property<string>("EnderecoCidade")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("endereco_cidade");

                    b.Property<string>("EnderecoComplemento")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("endereco_complemento");

                    b.Property<string>("EnderecoLogradouro")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("endereco_logradouro");

                    b.Property<string>("EnderecoNumero")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("endereco_numero");

                    b.Property<string>("EnderecoUf")
                        .HasColumnType("character(2)")
                        .HasColumnName("endereco_uf")
                        .IsFixedLength();

                    b.Property<string>("NomeFantasia")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome_fantasia");

                    b.Property<short>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_condominio");

                    b.HasIndex("ActivatedByUserId")
                        .HasDatabaseName("ix_condominio_activated_by_user_id");

                    b.HasIndex("Cnpj")
                        .IsUnique()
                        .HasDatabaseName("idx_condominio_cnpj_unique");

                    b.HasIndex("CreatedByUserId")
                        .HasDatabaseName("ix_condominio_created_by_user_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("idx_condominio_status");

                    b.ToTable("condominio", (string)null);
                });

            modelBuilder.Entity("PortaBox.Modules.Gestao.Domain.OptInDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("content_type");

                    b.Property<short>("Kind")
                        .HasColumnType("smallint")
                        .HasColumnName("kind");

                    b.Property<string>("Sha256")
                        .IsRequired()
                        .HasColumnType("character(64)")
                        .HasColumnName("sha256")
                        .IsFixedLength();

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("size_bytes");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("storage_key");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UploadedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("uploaded_at");

                    b.Property<Guid>("UploadedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("uploaded_by_user_id");

                    b.HasKey("Id")
                        .HasName("pk_opt_in_document");

                    b.HasIndex("UploadedByUserId")
                        .HasDatabaseName("ix_opt_in_document_uploaded_by_user_id");

                    b.HasIndex("TenantId", "UploadedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("idx_opt_in_document_tenant_id_uploaded_at_desc");

                    b.ToTable("opt_in_document", (string)null);
                });

            modelBuilder.Entity("PortaBox.Modules.Gestao.Domain.OptInRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateOnly>("DataAssembleia")
                        .HasColumnType("date")
                        .HasColumnName("data_assembleia");

                    b.Property<DateOnly>("DataTermo")
                        .HasColumnType("date")
                        .HasColumnName("data_termo");

                    b.Property<string>("QuorumDescricao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("quorum_descricao");

                    b.Property<DateTimeOffset>("RegisteredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("registered_at");

                    b.Property<Guid>("RegisteredByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("registered_by_user_id");

                    b.Property<string>("SignatarioCpf")
                        .IsRequired()
                        .HasColumnType("character(11)")
                        .HasColumnName("signatario_cpf")
                        .IsFixedLength();

                    b.Property<string>("SignatarioNome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("signatario_nome");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_opt_in_record");

                    b.HasIndex("RegisteredByUserId")
                        .HasDatabaseName("ix_opt_in_record_registered_by_user_id");

                    b.HasIndex("TenantId")
                        .IsUnique()
                        .HasDatabaseName("idx_opt_in_record_tenant_id_unique");

                    b.ToTable("opt_in_record", (string)null);
                });

            modelBuilder.Entity("PortaBox.Modules.Gestao.Domain.Sindico", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CelularE164")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("celular_e164");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("NomeCompleto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome_completo");

                    b.Property<short>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_sindico");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("idx_sindico_tenant_id");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_sindico_user_id");

                    b.ToTable("sindico", (string)null);
                });

            modelBuilder.Entity("PortaBox.Modules.Gestao.Domain.TenantAuditEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<short>("EventKind")
                        .HasColumnType("smallint")
                        .HasColumnName("event_kind");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata_json");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<Guid>("PerformedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("performed_by_user_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_tenant_audit_log");

                    b.HasIndex("PerformedByUserId")
                        .HasDatabaseName("ix_tenant_audit_log_performed_by_user_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_tenant_audit_log_tenant_id");

                    b.ToTable("tenant_audit_log", (string)null);
                });

            modelBuilder.Entity("PortaBox.Modules.Gestao.Domain.Unidades.Unidade", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Andar")
                        .HasColumnType("integer")
                        .HasColumnName("andar");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<Guid>("BlocoId")
                        .HasColumnType("uuid")
                        .HasColumnName("bloco_id");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<Guid>("CriadoPor")
                        .HasColumnType("uuid")
                        .HasColumnName("criado_por");

                    b.Property<DateTime?>("InativadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("inativado_em");

                    b.Property<Guid?>("InativadoPor")
                        .HasColumnType("uuid")
                        .HasColumnName("inativado_por");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("varchar(5)")
                        .HasColumnName("numero");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_unidade");

                    b.HasIndex("BlocoId")
                        .HasDatabaseName("idx_unidade_bloco");

                    b.HasIndex("CriadoPor")
                        .HasDatabaseName("ix_unidade_criado_por");

                    b.HasIndex("InativadoPor")
                        .HasDatabaseName("ix_unidade_inativado_por");

                    b.HasIndex("TenantId", "BlocoId", "Andar", "Numero")
                        .IsUnique()
                        .HasDatabaseName("idx_unidade_canonica_ativa")
                        .HasFilter("ativo = true");

                    b.ToTable("unidade", null, t =>
                        {
                            t.HasCheckConstraint("ck_unidade_andar_non_negative", "andar >= 0");
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("PortaBox.Infrastructure.Identity.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_role_claims_asp_net_roles_role_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("PortaBox.Infrastructure.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_claims_asp_net_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("PortaBox.Infrastructure.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_logins_asp_net_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("PortaBox.Infrastructure.Identity.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_roles_asp_net_roles_role_id");

                    b.HasOne("PortaBox.Infrastructure.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_roles_asp_net_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("PortaBox.Infrastructure.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_tokens_asp_net_users_user_id");
                });

            modelBuilder.Entity("PortaBox.Infrastructure.Identity.AppUser", b =>
                {
                    b.HasOne("PortaBox.Modules.Gestao.Domain.Condominio", null)
                        .WithMany()
                        .HasForeignKey("SindicoTenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_asp_net_users_condominios_sindico_tenant_id");
                });

            modelBuilder.Entity("PortaBox.Infrastructure.MagicLinks.MagicLink", b =>
                {
                    b.HasOne("PortaBox.Infrastructure.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_magic_link_asp_net_users_user_id");
                });

            modelBuilder.Entity("PortaBox.Modules.Gestao.Domain.Blocos.Bloco", b =>
                {
                    b.HasOne("PortaBox.Modules.Gestao.Domain.Condominio", null)
                        .WithMany()
                        .HasForeignKey("CondominioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_bloco_condominios_condominio_id");

                    b.HasOne("PortaBox.Infrastructure.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("CriadoPor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_bloco_asp_net_users_criado_por");

                    b.HasOne("PortaBox.Infrastructure.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("InativadoPor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_bloco_asp_net_users_inativado_por");
                });

            modelBuilder.Entity("PortaBox.Modules.Gestao.Domain.Condominio", b =>
                {
                    b.HasOne("PortaBox.Infrastructure.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("ActivatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_condominio_asp_net_users_activated_by_user_id");

                    b.HasOne("PortaBox.Infrastructure.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_condominio_asp_net_users_created_by_user_id");
                });

            modelBuilder.Entity("PortaBox.Modules.Gestao.Domain.OptInDocument", b =>
                {
                    b.HasOne("PortaBox.Modules.Gestao.Domain.Condominio", "Condominio")
                        .WithMany("OptInDocuments")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_opt_in_document_condominio_tenant_id");

                    b.HasOne("PortaBox.Infrastructure.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UploadedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_opt_in_document_asp_net_users_uploaded_by_user_id");

                    b.Navigation("Condominio");
                });

            modelBuilder.Entity("PortaBox.Modules.Gestao.Domain.OptInRecord", b =>
                {
                    b.HasOne("PortaBox.Infrastructure.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("RegisteredByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_opt_in_record_asp_net_users_registered_by_user_id");

                    b.HasOne("PortaBox.Modules.Gestao.Domain.Condominio", "Condominio")
                        .WithOne("OptInRecord")
                        .HasForeignKey("PortaBox.Modules.Gestao.Domain.OptInRecord", "TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_opt_in_record_condominio_tenant_id");

                    b.Navigation("Condominio");
                });

            modelBuilder.Entity("PortaBox.Modules.Gestao.Domain.Sindico", b =>
                {
                    b.HasOne("PortaBox.Modules.Gestao.Domain.Condominio", "Condominio")
                        .WithMany("Sindicos")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sindico_condominio_tenant_id");

                    b.HasOne("PortaBox.Infrastructure.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_sindico_asp_net_users_user_id");

                    b.Navigation("Condominio");
                });

            modelBuilder.Entity("PortaBox.Modules.Gestao.Domain.TenantAuditEntry", b =>
                {
                    b.HasOne("PortaBox.Infrastructure.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("PerformedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_tenant_audit_log_asp_net_users_performed_by_user_id");

                    b.HasOne("PortaBox.Modules.Gestao.Domain.Condominio", "Condominio")
                        .WithMany("TenantAuditEntries")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_tenant_audit_log_condominio_tenant_id");

                    b.Navigation("Condominio");
                });

            modelBuilder.Entity("PortaBox.Modules.Gestao.Domain.Unidades.Unidade", b =>
                {
                    b.HasOne("PortaBox.Modules.Gestao.Domain.Blocos.Bloco", null)
                        .WithMany()
                        .HasForeignKey("BlocoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_unidade_bloco_bloco_id");

                    b.HasOne("PortaBox.Infrastructure.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("CriadoPor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_unidade_asp_net_users_criado_por");

                    b.HasOne("PortaBox.Infrastructure.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("InativadoPor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_unidade_asp_net_users_inativado_por");
                });

            modelBuilder.Entity("PortaBox.Modules.Gestao.Domain.Condominio", b =>
                {
                    b.Navigation("OptInDocuments");

                    b.Navigation("OptInRecord");

                    b.Navigation("Sindicos");

                    b.Navigation("TenantAuditEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
