// Generated from .compozy/tasks/f02-gestao-blocos-unidades/api-contract.yaml.
// Regenerate with: pnpm --filter @portabox/api-client generate:types
/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/condominios/{condominioId}/estrutura": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Identificador único do condomínio (tenant) */
                condominioId: components["parameters"]["CondominioId"];
            };
            cookie?: never;
        };
        /**
         * Ler árvore de estrutura (síndico)
         * @description Retorna a árvore hierárquica completa do condomínio: blocos → andares → unidades.
         *     Agrupamento e ordenação feitos no servidor (blocos alfabético; andares numérico; unidades por andar + número semântico).
         *     Apenas o síndico do tenant pode consumir este endpoint.
         */
        get: operations["getEstrutura"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/condominios/{condominioId}/blocos": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Identificador único do condomínio (tenant) */
                condominioId: components["parameters"]["CondominioId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Criar bloco
         * @description Cria um novo bloco vinculado ao condomínio. Nome único entre blocos ativos do tenant.
         *     Unicidade enforced via partial unique index no Postgres (ADR-007).
         */
        post: operations["criarBloco"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/condominios/{condominioId}/blocos/{blocoId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Identificador único do condomínio (tenant) */
                condominioId: components["parameters"]["CondominioId"];
                /** @description Identificador único do bloco */
                blocoId: components["parameters"]["BlocoId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Renomear bloco
         * @description Altera o nome de exibição do bloco. Apenas o nome é editável (ADR-003);
         *     unidades vinculadas permanecem intactas. Novo nome deve ser distinto do atual
         *     e único entre blocos ativos do tenant.
         */
        patch: operations["renomearBloco"];
        trace?: never;
    };
    "/condominios/{condominioId}/blocos/{blocoId}:inativar": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Identificador único do condomínio (tenant) */
                condominioId: components["parameters"]["CondominioId"];
                /** @description Identificador único do bloco */
                blocoId: components["parameters"]["BlocoId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Inativar bloco
         * @description Executa soft-delete do bloco. Sem cascata no MVP — unidades ativas permanecem e
         *     precisam ser inativadas separadamente. Criação de novas unidades no bloco passa
         *     a ser bloqueada (422).
         */
        post: operations["inativarBloco"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/condominios/{condominioId}/blocos/{blocoId}:reativar": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Identificador único do condomínio (tenant) */
                condominioId: components["parameters"]["CondominioId"];
                /** @description Identificador único do bloco */
                blocoId: components["parameters"]["BlocoId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reativar bloco
         * @description Reverte inativação. Rejeita com 409 se já existir outro bloco ativo com o mesmo
         *     nome no tenant (conflito canônico; partial unique index).
         */
        post: operations["reativarBloco"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/condominios/{condominioId}/blocos/{blocoId}/unidades": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Identificador único do condomínio (tenant) */
                condominioId: components["parameters"]["CondominioId"];
                /** @description Identificador único do bloco */
                blocoId: components["parameters"]["BlocoId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Criar unidade
         * @description Cria uma nova unidade no bloco indicado. Bloco deve estar ativo (caso contrário 422).
         *     A tripla (blocoId, andar, numero) deve ser única entre unidades ativas do tenant.
         *     Número é normalizado para caixa alta no servidor (ADR-002).
         */
        post: operations["criarUnidade"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/condominios/{condominioId}/blocos/{blocoId}/unidades/{unidadeId}:inativar": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Identificador único do condomínio (tenant) */
                condominioId: components["parameters"]["CondominioId"];
                /** @description Identificador único do bloco */
                blocoId: components["parameters"]["BlocoId"];
                /** @description Identificador único da unidade */
                unidadeId: components["parameters"]["UnidadeId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Inativar unidade
         * @description Soft-delete de unidade. Moradores associados permanecem vinculados — gestão de
         *     moradores é responsabilidade de F03.
         */
        post: operations["inativarUnidade"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/condominios/{condominioId}/blocos/{blocoId}/unidades/{unidadeId}:reativar": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Identificador único do condomínio (tenant) */
                condominioId: components["parameters"]["CondominioId"];
                /** @description Identificador único do bloco */
                blocoId: components["parameters"]["BlocoId"];
                /** @description Identificador único da unidade */
                unidadeId: components["parameters"]["UnidadeId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reativar unidade
         * @description Reverte inativação. Rejeita com 409 se já existir outra unidade ativa com a mesma
         *     tripla (bloco, andar, número) no tenant. Exige que o bloco alvo esteja ativo (422 caso contrário).
         */
        post: operations["reativarUnidade"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/condominios/{condominioId}/estrutura": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Identificador único do condomínio (tenant) */
                condominioId: components["parameters"]["CondominioId"];
            };
            cookie?: never;
        };
        /**
         * Ler estrutura de qualquer tenant (operador)
         * @description Mesmo shape de resposta de `GET /condominios/{id}/estrutura`, porém acessível por operadores
         *     da plataforma (role `Operator`) em qualquer tenant, sem capacidade de escrita (ADR-005).
         *     O `condominioId` no path é usado como tenant explícito.
         */
        get: operations["getEstruturaAdmin"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Árvore hierárquica completa do condomínio */
        Estrutura: {
            /**
             * Format: uuid
             * @description Identificador do condomínio
             * @example 550e8400-e29b-41d4-a716-446655440000
             */
            condominioId: string;
            /**
             * @description Nome de exibição do condomínio
             * @example Condomínio Residencial Alfa
             */
            nomeFantasia: string;
            /** @description Blocos do condomínio. Ordenados alfabeticamente pelo nome. */
            blocos: components["schemas"]["BlocoNode"][];
            /**
             * Format: date-time
             * @description Timestamp da geração da resposta (ISO 8601 UTC)
             * @example 2026-04-18T12:34:56Z
             */
            geradoEm: string;
        };
        /** @description Nó de bloco dentro da árvore de estrutura */
        BlocoNode: {
            /**
             * Format: uuid
             * @description Identificador do bloco
             * @example aa111111-2222-3333-4444-555555555555
             */
            id: string;
            /**
             * @description Nome de exibição
             * @example Bloco A
             */
            nome: string;
            /**
             * @description Status do bloco. Inativos só aparecem quando `includeInactive=true`.
             * @example true
             */
            ativo: boolean;
            /** @description Andares do bloco, ordenados numericamente crescente */
            andares: components["schemas"]["AndarNode"][];
        };
        /** @description Agrupamento interno de unidades por andar dentro de um bloco */
        AndarNode: {
            /**
             * @description Número do andar (0 = térreo)
             * @example 2
             */
            andar: number;
            /** @description Unidades do andar, ordenadas semanticamente (parte numérica primeiro, depois sufixo alfabético) */
            unidades: components["schemas"]["UnidadeLeaf"][];
        };
        /** @description Folha de unidade dentro da árvore de estrutura */
        UnidadeLeaf: {
            /**
             * Format: uuid
             * @description Identificador da unidade
             * @example bb222222-3333-4444-5555-666666666666
             */
            id: string;
            /**
             * @description Número da unidade; aceita sufixo alfabético maiúsculo (regex `^[0-9]{1,4}[A-Z]?$`)
             * @example 201A
             */
            numero: string;
            /**
             * @description Status da unidade
             * @example true
             */
            ativo: boolean;
        };
        /** @description Bloco (response de mutações — Create/Rename/Inativar/Reativar) */
        Bloco: {
            /**
             * Format: uuid
             * @description Identificador do bloco
             * @example aa111111-2222-3333-4444-555555555555
             */
            id: string;
            /**
             * Format: uuid
             * @description Condomínio ao qual o bloco pertence
             * @example 550e8400-e29b-41d4-a716-446655440000
             */
            condominioId: string;
            /**
             * @description Nome de exibição (mutável via `PATCH`)
             * @example Bloco A
             */
            nome: string;
            /**
             * @description Status do bloco
             * @example true
             */
            ativo: boolean;
            /**
             * Format: date-time
             * @description Timestamp de inativação; `null` quando ativo
             * @example null
             */
            inativadoEm?: string | null;
        };
        /** @description Unidade (response de mutações — Create/Inativar/Reativar). Imutável após criação (ADR-003). */
        Unidade: {
            /**
             * Format: uuid
             * @description Identificador da unidade
             * @example bb222222-3333-4444-5555-666666666666
             */
            id: string;
            /**
             * Format: uuid
             * @description Bloco ao qual a unidade pertence
             * @example aa111111-2222-3333-4444-555555555555
             */
            blocoId: string;
            /**
             * @description Andar (imutável após criação)
             * @example 2
             */
            andar: number;
            /**
             * @description Número canônico (imutável após criação). Caixa alta.
             * @example 201A
             */
            numero: string;
            /**
             * @description Status da unidade
             * @example true
             */
            ativo: boolean;
            /**
             * Format: date-time
             * @description Timestamp de inativação; `null` quando ativa
             * @example null
             */
            inativadoEm?: string | null;
        };
        CreateBlocoRequest: {
            /**
             * @description Nome do bloco (único entre ativos do tenant; trim aplicado no servidor)
             * @example Bloco A
             */
            nome: string;
        };
        RenameBlocoRequest: {
            /**
             * @description Novo nome; deve ser distinto do atual e único entre ativos do tenant
             * @example Torre Alfa
             */
            nome: string;
        };
        CreateUnidadeRequest: {
            /**
             * @description Andar da unidade (0 = térreo)
             * @example 2
             */
            andar: number;
            /**
             * @description Número da unidade. Aceita caixa mista no input; normalizado para caixa alta no servidor.
             * @example 201A
             */
            numero: string;
        };
        /** @description Payload de erro RFC 7807 (application/problem+json) */
        ProblemDetails: {
            /**
             * Format: uri
             * @description URI identificando o tipo do problema
             * @example https://portabox.app/problems/canonical-conflict
             */
            type: string;
            /**
             * @description Título curto em pt-BR (não muda entre ocorrências do mesmo `type`)
             * @example Conflito canônico
             */
            title: string;
            /**
             * @description HTTP status code espelhado aqui para conveniência
             * @example 409
             */
            status: number;
            /**
             * @description Descrição contextual em pt-BR sobre esta ocorrência específica
             * @example Já existe unidade ativa para Bloco A / Andar 2 / Apto 201.
             */
            detail?: string | null;
            /**
             * @description URI da ocorrência (path chamado)
             * @example /api/v1/condominios/550e8400.../blocos/aa111111.../unidades
             */
            instance?: string | null;
            /**
             * @description TraceId OpenTelemetry para correlação (presente em 5xx)
             * @example 00-4bf92f3577b34da6a3ce929d0e0e4736-00f067aa0ba902b7-01
             */
            traceId?: string | null;
        };
        ValidationProblemDetails: components["schemas"]["ProblemDetails"] & {
            /**
             * @description Erros agrupados por nome do campo. Cada campo lista uma ou mais mensagens em pt-BR.
             * @example {
             *       "nome": [
             *         "O nome é obrigatório",
             *         "O nome deve ter no máximo 50 caracteres"
             *       ],
             *       "andar": [
             *         "O andar deve ser maior ou igual a 0"
             *       ]
             *     }
             */
            errors: {
                [key: string]: string[];
            };
        };
    };
    responses: {
        /** @description Requisição inválida — erro de validação de campos */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "https://portabox.app/problems/validation-error",
                 *       "title": "Falha de validação",
                 *       "status": 400,
                 *       "detail": "Um ou mais campos estão inválidos",
                 *       "instance": "/api/v1/condominios/550e8400-e29b-41d4-a716-446655440000/blocos",
                 *       "errors": {
                 *         "nome": [
                 *           "O nome é obrigatório"
                 *         ]
                 *       }
                 *     }
                 */
                "application/problem+json": components["schemas"]["ValidationProblemDetails"];
            };
        };
        /** @description Não autenticado — token ausente, expirado ou inválido */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "https://portabox.app/problems/unauthorized",
                 *       "title": "Não autorizado",
                 *       "status": 401,
                 *       "detail": "Token de autenticação inválido ou expirado"
                 *     }
                 */
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description Autenticado mas sem permissão para a operação (role errada ou tenant alheio) */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "https://portabox.app/problems/forbidden",
                 *       "title": "Acesso negado",
                 *       "status": 403,
                 *       "detail": "Você não tem permissão para executar esta operação"
                 *     }
                 */
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description Recurso não encontrado (ou existente em outro tenant — mesma resposta para não vazar existência) */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "https://portabox.app/problems/not-found",
                 *       "title": "Recurso não encontrado",
                 *       "status": 404,
                 *       "detail": "Bloco não encontrado"
                 *     }
                 */
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description Conflito de estado — unicidade canônica violada em criação ou reativação */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "https://portabox.app/problems/canonical-conflict",
                 *       "title": "Conflito canônico",
                 *       "status": 409,
                 *       "detail": "Já existe unidade ativa para Bloco A / Andar 2 / Apto 201. Inative-a antes de reativar esta."
                 *     }
                 */
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /**
         * @description Requisição bem formada mas impossível de processar por estado atual:
         *     - Tentativa de inativar entidade já inativa
         *     - Tentativa de reativar entidade já ativa
         *     - Tentativa de criar unidade em bloco inativo
         */
        UnprocessableEntity: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "https://portabox.app/problems/invalid-transition",
                 *       "title": "Transição inválida",
                 *       "status": 422,
                 *       "detail": "Não é possível criar unidade em bloco inativo. Reative o bloco antes."
                 *     }
                 */
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description Erro interno inesperado */
        InternalServerError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "https://portabox.app/problems/internal-error",
                 *       "title": "Erro interno do servidor",
                 *       "status": 500,
                 *       "detail": "Ocorreu um erro inesperado. Tente novamente mais tarde.",
                 *       "traceId": "00-4bf92f3577b34da6a3ce929d0e0e4736-00f067aa0ba902b7-01"
                 *     }
                 */
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
    };
    parameters: {
        /** @description Identificador único do condomínio (tenant) */
        CondominioId: string;
        /** @description Identificador único do bloco */
        BlocoId: string;
        /** @description Identificador único da unidade */
        UnidadeId: string;
        /** @description Quando `true`, inclui blocos e unidades inativos na resposta. Default `false`. */
        IncludeInactive: boolean;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getEstrutura: {
        parameters: {
            query?: {
                /** @description Quando `true`, inclui blocos e unidades inativos na resposta. Default `false`. */
                includeInactive?: components["parameters"]["IncludeInactive"];
            };
            header?: never;
            path: {
                /** @description Identificador único do condomínio (tenant) */
                condominioId: components["parameters"]["CondominioId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Árvore retornada com sucesso */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Estrutura"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerError"];
        };
    };
    criarBloco: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Identificador único do condomínio (tenant) */
                condominioId: components["parameters"]["CondominioId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateBlocoRequest"];
            };
        };
        responses: {
            /** @description Bloco criado com sucesso */
            201: {
                headers: {
                    /** @description URI do bloco criado */
                    Location?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Bloco"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            500: components["responses"]["InternalServerError"];
        };
    };
    renomearBloco: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Identificador único do condomínio (tenant) */
                condominioId: components["parameters"]["CondominioId"];
                /** @description Identificador único do bloco */
                blocoId: components["parameters"]["BlocoId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RenameBlocoRequest"];
            };
        };
        responses: {
            /** @description Bloco renomeado */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Bloco"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["UnprocessableEntity"];
            500: components["responses"]["InternalServerError"];
        };
    };
    inativarBloco: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Identificador único do condomínio (tenant) */
                condominioId: components["parameters"]["CondominioId"];
                /** @description Identificador único do bloco */
                blocoId: components["parameters"]["BlocoId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Bloco inativado */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Bloco"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["UnprocessableEntity"];
            500: components["responses"]["InternalServerError"];
        };
    };
    reativarBloco: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Identificador único do condomínio (tenant) */
                condominioId: components["parameters"]["CondominioId"];
                /** @description Identificador único do bloco */
                blocoId: components["parameters"]["BlocoId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Bloco reativado */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Bloco"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["UnprocessableEntity"];
            500: components["responses"]["InternalServerError"];
        };
    };
    criarUnidade: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Identificador único do condomínio (tenant) */
                condominioId: components["parameters"]["CondominioId"];
                /** @description Identificador único do bloco */
                blocoId: components["parameters"]["BlocoId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateUnidadeRequest"];
            };
        };
        responses: {
            /** @description Unidade criada com sucesso */
            201: {
                headers: {
                    /** @description URI da unidade criada */
                    Location?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Unidade"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["UnprocessableEntity"];
            500: components["responses"]["InternalServerError"];
        };
    };
    inativarUnidade: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Identificador único do condomínio (tenant) */
                condominioId: components["parameters"]["CondominioId"];
                /** @description Identificador único do bloco */
                blocoId: components["parameters"]["BlocoId"];
                /** @description Identificador único da unidade */
                unidadeId: components["parameters"]["UnidadeId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Unidade inativada */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Unidade"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["UnprocessableEntity"];
            500: components["responses"]["InternalServerError"];
        };
    };
    reativarUnidade: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Identificador único do condomínio (tenant) */
                condominioId: components["parameters"]["CondominioId"];
                /** @description Identificador único do bloco */
                blocoId: components["parameters"]["BlocoId"];
                /** @description Identificador único da unidade */
                unidadeId: components["parameters"]["UnidadeId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Unidade reativada */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Unidade"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["UnprocessableEntity"];
            500: components["responses"]["InternalServerError"];
        };
    };
    getEstruturaAdmin: {
        parameters: {
            query?: {
                /** @description Quando `true`, inclui blocos e unidades inativos na resposta. Default `false`. */
                includeInactive?: components["parameters"]["IncludeInactive"];
            };
            header?: never;
            path: {
                /** @description Identificador único do condomínio (tenant) */
                condominioId: components["parameters"]["CondominioId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Árvore retornada com sucesso */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Estrutura"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerError"];
        };
    };
}
